version: '3.3'

services:
  andresStoreDb:
    image: postgres:13
    environment:
      - POSTGRES_DB=andres_store_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5430:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
