version: '3.3'

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=andres_store_db
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
    ports:
      - '5430:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  mysql:
    image: mysql:5
    environment:
      - MYSQL_DATABASE=andres_store_db
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_data:/var/lib/mysql
